# TableTalk Configuration

# Database settings
database:
  path: "./database/metadata.duckdb"
  schema: "main"

# LLM settings
llm:
  model: "phi3:mini"
  base_url: "http://localhost:11434"
  temperature: 0.1
  max_tokens: 1000

# File scanning settings
scanner:
  supported_formats: ["csv", "parquet"]
  max_file_size_mb: 100
  sample_size: 1000

# CLI settings
cli:
  prompt: "TableTalk> "
  max_history: 50

# Logging
logging:
  level: "INFO"
  file: "./logs/tabletalk.log"
