# TableTalk Configuration

# Database settings
database:
  path: "./database/metadata.duckdb"
  schema: "main"

# LLM settings
llm:
  model: "phi4-mini-fc"  # Use function calling enabled model
  base_url: "http://localhost:11434"
  temperature: 0.1
  max_tokens: 3000
  timeout: 120  # API call timeout in seconds (default: 120)
  strategy_type: null  # Options: "function_calling", "structured_output", or null for auto-detection

# LangGraph settings (Phase 1)
langgraph:
  enabled: true
  default_workflow: "basic_query"
  max_retry_count: 2
  execution_timeout: 60  # Workflow execution timeout

# File scanning settings
scanner:
  supported_formats: ["csv", "parquet"]
  max_file_size_mb: 100
  sample_size: 1000

# CLI settings
cli:
  prompt: "TableTalk> "
  max_history: 50

# Logging
logging:
  level: "DEBUG"
  file: "./logs/tabletalk.log"

# Export settings
export:
  enabled: true
  auto_export_threshold: 20  # Lines to trigger auto-export
  base_path: "./exports"       # Export directory
