# TableTalk Configuration

# Database settings
database:
  path: "./database/metadata.duckdb"
  schema: "main"

# LLM settings
llm:
  model: "phi4-mini-fc"  # Use function calling enabled model
  base_url: "http://localhost:11434"
  temperature: 0.1
  max_tokens: 3000
  strategy_type: sql_agent_simple  # Options: "function_calling", "structured_output", "sql_agent", "sql_agent_langgraph", "sql_agent_simple", or null for auto-detection

# File scanning settings
scanner:
  supported_formats: ["csv", "parquet"]
  max_file_size_mb: 100
  sample_size: 1000

# CLI settings
cli:
  prompt: "TableTalk> "
  max_history: 50

# Logging
logging:
  level: "INFO"
  file: "./logs/tabletalk.log"
